// a function to lookup for existing emails and returns the user if its registered
const getUserByEmail = (email, database) => {
  for (const key in database) {
    if (database[key].email === email) {
      return database[key];
    }
  }
  return undefined;
};

// a function that generates an object for a given user with all the urls generated by him
const userURLs = (user, database) => {
  const urls = {};
  for (const shortURL in database) {
    const userID = database[shortURL].userID;
    if (user && userID === user.id) {
      const { longURL } = database[shortURL];
      urls[shortURL] = { longURL };
    }
  }
  return urls;
};

// a function that returns a string of 6 random alphanumeric characters
const generateRandomString = () => {
  return Math.random().toString(36).substring(2, 8);
};

module.exports = { getUserByEmail, userURLs, generateRandomString };